[oslo_messaging_notifications]
driver = messagingv2
topics = notifications
transport_url = rabbit://openstack:CHANGE_ME@127.0.0.1:5672/

[event_notifications]
driver = messagingv2
transport_url = rabbit://openstack:CHANGE_ME@127.0.0.1:5672/
topics = notifications

